name: tempoloco
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase 
  firebase_core: ^1.20.0
  firebase_auth: ^3.5.1
  cloud_firestore: ^3.4.1

  lints: ^2.0.0
  get: ^4.6.1
  lottie: ^1.2.2
  json_annotation: ^4.6.0
  spotify: ^0.7.2
  get_it: ^7.2.0
  hive: ^2.2.3
  path_provider: ^2.0.11
  email_validator: ^2.1.16
  custom_navigation_bar: ^0.8.2
  flutter_feather_icons: ^2.0.0+1
  copy_with_extension: ^4.0.2
  just_audio: ^0.9.29
  multiavatar: ^0.1.5
  flutter_svg: ^1.1.6
  share_plus: ^6.0.1
  firebase_remote_config: ^2.0.20
  fl_chart: ^0.55.2
  cupertino_icons: ^1.0.5
  smooth_page_indicator: ^1.0.0+2
  soundpool: ^2.3.0
  mixpanel_flutter: ^2.0.0
  sentry_flutter: ^6.16.0
  wiredash: ^1.5.0
  package_info_plus: ^3.0.2

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  copy_with_extension_gen: ^4.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
    - assets/images/
  
  fonts:
    - family: SF-Pro-Display
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Regular.ttf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Semibold.ttf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Bold.ttf
          weight: 700
